import { Passage, Question, QuizItem } from './types';

export const LOCAL_DICTIONARY: Record<string, { t: string, d: string, s?: string[] }> = {
  // --- Common Stopwords & Basics ---
  "the": { t: "определенный артикль", d: "Used to point to something specific.", s: [] },
  "a": { t: "неопределенный артикль", d: "Used to point to something non-specific.", s: [] },
  "an": { t: "неопределенный артикль", d: "Form of 'a' before a vowel.", s: [] },
  "of": { t: "из / о", d: "Expressing relationship between a part and a whole.", s: [] },
  "and": { t: "и", d: "Used to connect words.", s: [] },
  "to": { t: "в / к / чтобы", d: "Expressing motion or purpose.", s: [] },
  "in": { t: "в", d: "Inside.", s: [] },
  "is": { t: "есть", d: "Third person singular present of be.", s: [] },
  "that": { t: "что / тот", d: "Used to identify a specific person or thing.", s: [] },
  "for": { t: "для", d: "With the object or purpose of.", s: [] },
  "it": { t: "это", d: "Used to refer to a thing previously mentioned.", s: [] },
  "as": { t: "как", d: "Used in comparisons.", s: [] },
  "are": { t: "есть (мн.ч.)", d: "Second person singular present and plural present of be.", s: [] },
  "on": { t: "на", d: "Physically in contact with and supported by.", s: [] },
  "with": { t: "с", d: "Accompanied by.", s: [] },
  "this": { t: "этот", d: "Used to identify a specific person or thing close at hand.", s: [] },
  "was": { t: "был", d: "Past of be.", s: [] },
  "were": { t: "были", d: "Past of be (plural).", s: [] },
  "by": { t: "по / у / к", d: "Identifying the agent performing an action.", s: [] },
  "not": { t: "не", d: "Used to form a negative.", s: [] },
  "but": { t: "но", d: "Used to introduce a phrase contrasting with what has already been mentioned.", s: [] },
  "have": { t: "иметь", d: "Possess, own, or hold.", s: [] },
  "has": { t: "имеет", d: "Third person singular present of have.", s: [] },
  "had": { t: "имел", d: "Past of have.", s: [] },
  "be": { t: "быть", d: "Exist.", s: [] },
  "been": { t: "был", d: "Past participle of be.", s: [] },
  "being": { t: "бытие / будучи", d: "Existence.", s: [] },
  "which": { t: "который", d: "Asking for information specifying one or more people or things.", s: [] },
  "from": { t: "из", d: "Indicating the point in space at which a journey starts.", s: [] },
  "at": { t: "в / на", d: "Expressing location or arrival.", s: [] },
  "or": { t: "или", d: "Used to link alternatives.", s: [] },
  "more": { t: "больше", d: "A greater or additional amount.", s: [] },
  "can": { t: "мочь", d: "Be able to.", s: [] },
  "could": { t: "мог", d: "Past of can.", s: [] },
  "will": { t: "будет", d: "Expressing the future tense.", s: [] },
  "would": { t: "бы", d: "Indicates the consequence of an imagined event.", s: [] },
  "their": { t: "их", d: "Belonging to them.", s: [] },
  "its": { t: "его / ее", d: "Belonging to it.", s: [] },
  "one": { t: "один", d: "The lowest cardinal number.", s: [] },
  "two": { t: "два", d: "The number 2.", s: [] },
  "three": { t: "три", d: "The number 3.", s: [] },
  "if": { t: "если", d: "Introducing a conditional clause.", s: [] },
  "they": { t: "они", d: "Used to refer to two or more people or things.", s: [] },
  "them": { t: "их", d: "Object case of they.", s: [] },
  "so": { t: "так / итак", d: "To such a great extent.", s: [] },
  "all": { t: "все", d: "The whole quantity or extent of.", s: [] },
  "when": { t: "когда", d: "At what time.", s: [] },
  "only": { t: "только", d: "And no one or nothing more besides.", s: [] },
  "those": { t: "те", d: "Plural of that.", s: [] },
  "such": { t: "такой", d: "Of the type previously mentioned.", s: [] },
  "into": { t: "в", d: "Expressing movement or action with the result that someone or something becomes enclosed.", s: [] },
  "than": { t: "чем", d: "Introducing the second element in a comparison.", s: [] },
  "also": { t: "также", d: "In addition; too.", s: [] },
  "most": { t: "большинство", d: "Greatest in amount, quantity, or degree.", s: [] },
  "other": { t: "другой", d: "Different or distinct from one already mentioned.", s: [] },
  "some": { t: "некоторые", d: "An unspecified amount or number of.", s: [] },
  "no": { t: "нет", d: "Not any.", s: [] },
  "new": { t: "новый", d: "Not existing before.", s: [] },
  "even": { t: "даже", d: "Used to emphasize something surprising or extreme.", s: [] },
  "like": { t: "как / нравиться", d: "Having the same characteristics or qualities as; similar to.", s: [] },
  "these": { t: "эти", d: "Plural of this.", s: [] },
  "then": { t: "тогда / затем", d: "At that time; after that.", s: [] },
  "up": { t: "вверх", d: "Towards a higher place or position.", s: [] },
  "out": { t: "наружу", d: "Moving or appearing to move away from a particular place.", s: [] },
  "do": { t: "делать", d: "Perform an action.", s: [] },
  "does": { t: "делает", d: "Third person singular present of do.", s: [] },
  "what": { t: "что", d: "Asking for information specifying something.", s: [] },
  "there": { t: "там", d: "In, at, or to that place or position.", s: [] },
  "time": { t: "время", d: "The indefinite continued progress of existence.", s: [] },
  "just": { t: "просто", d: "Exactly.", s: [] },
  "where": { t: "где", d: "In or to what place or position.", s: [] },
  "now": { t: "сейчас", d: "At the present time.", s: [] },
  "much": { t: "много", d: "A large amount.", s: [] },
  "well": { t: "хорошо", d: "In a good or satisfactory way.", s: [] },
  "however": { t: "однако", d: "Used to introduce a statement that contrasts with something said previously.", s: [] },
  "many": { t: "много", d: "A large number of.", s: [] },
  "people": { t: "люди", d: "Human beings in general.", s: [] },
  "because": { t: "потому что", d: "For the reason that.", s: [] },
  "very": { t: "очень", d: "Used for emphasis.", s: [] },
  "still": { t: "все еще", d: "Up to and including the present.", s: [] },
  "may": { t: "может", d: "Expressing possibility.", s: [] },
  "over": { t: "над", d: "Extending directly upwards from.", s: [] },
  "see": { t: "видеть", d: "Perceive with the eyes.", s: [] },
  "way": { t: "путь / способ", d: "A method, style, or manner of doing something.", s: [] },
  "work": { t: "работа", d: "Activity involving mental or physical effort.", s: [] },
  "through": { t: "через", d: "Moving in one side and out of the other side of.", s: [] },
  "change": { t: "изменение", d: "Make or become different.", s: [] },
  "large": { t: "большой", d: "Of considerable or relatively great size.", s: [] },
  "often": { t: "часто", d: "Frequently; many times.", s: [] },
  "different": { t: "различный", d: "Not the same as another.", s: [] },
  "found": { t: "нашел", d: "Past of find.", s: [] },
  "same": { t: "тот же", d: "Identical; not different.", s: [] },
  "study": { t: "исследование", d: "A detailed investigation and analysis.", s: [] },
  "each": { t: "каждый", d: "Every one of two or more people or things.", s: [] },
  "long": { t: "долгий", d: "Measuring a great distance from end to end.", s: [] },
  "made": { t: "сделанный", d: "Past of make.", s: [] },
  "between": { t: "между", d: "At, into, or across the space separating two objects.", s: [] },
  "city": { t: "город", d: "A large town.", s: [] },
  "cities": { t: "города", d: "Plural of city.", s: [] },
  "should": { t: "должен", d: "Used to indicate obligation.", s: [] },
  "since": { t: "с тех пор", d: "In the intervening period between.", s: [] },
  "own": { t: "собственный", d: "Belonging to oneself.", s: [] },
  "before": { t: "до", d: "During the period of time preceding.", s: [] },
  "must": { t: "должен", d: "Be obliged to.", s: [] },
  "back": { t: "назад", d: "In the opposite direction.", s: [] },
  "good": { t: "хороший", d: "To be desired or approved of.", s: [] },
  "high": { t: "высокий", d: "Of great vertical extent.", s: [] },
  "part": { t: "часть", d: "A piece or segment of something.", s: [] },
  "might": { t: "мог бы", d: "Used to express possibility.", s: [] },
  "problem": { t: "проблема", d: "A matter or situation regarded as unwelcome.", s: [] },
  "problems": { t: "проблемы", d: "Plural of problem.", s: [] },
  "against": { t: "против", d: "In opposition to.", s: [] },
  "place": { t: "место", d: "A particular position or point in space.", s: [] },
  "number": { t: "число", d: "An arithmetical value.", s: [] },
  "system": { t: "система", d: "A set of things working together.", s: [] },
  "systems": { t: "системы", d: "Plural of system.", s: [] },
  "during": { t: "в течение", d: "Throughout the course or duration of.", s: [] },
  "set": { t: "набор / установить", d: "Put, lay, or stand something in a specified place.", s: [] },
  "small": { t: "маленький", d: "Of a size that is less than normal.", s: [] },
  "every": { t: "каждый", d: "Used to refer to all the individual members of a set.", s: [] },
  "point": { t: "точка / указывать", d: "A dot or other small mark.", s: [] },
  "less": { t: "меньше", d: "A smaller amount of.", s: [] },
  "form": { t: "форма", d: "The visible shape or configuration of something.", s: [] },
  "fact": { t: "факт", d: "A thing that is known or proved to be true.", s: [] },
  "today": { t: "сегодня", d: "On or in the course of this present day.", s: [] },
  "too": { t: "тоже / слишком", d: "To a higher degree than is desirable.", s: [] },
  "little": { t: "маленький", d: "Small in size, amount, or degree.", s: [] },
  "become": { t: "становиться", d: "Begin to be.", s: [] },
  "around": { t: "вокруг", d: "Located or situated on every side.", s: [] },
  "under": { t: "под", d: "Extending or directly below.", s: [] },
  "away": { t: "прочь", d: "To or at a distance from a particular place.", s: [] },
  "process": { t: "процесс", d: "A series of actions or steps taken in order to achieve a particular end.", s: [] },
  "state": { t: "состояние / государство", d: "The particular condition that someone or something is in.", s: [] },
  "states": { t: "состояния", d: "Plural of state.", s: [] },
  "case": { t: "случай", d: "An instance of a particular situation.", s: [] },
  "cases": { t: "случаи", d: "Plural of case.", s: [] },
  "really": { t: "действительно", d: "In actual fact.", s: [] },
  "group": { t: "группа", d: "A number of people or things located close together.", s: [] },
  "why": { t: "почему", d: "For what reason.", s: [] },
  "effect": { t: "эффект", d: "A change which is a result or consequence of an action.", s: [] },
  "effects": { t: "эффекты", d: "Plural of effect.", s: [] },
  "use": { t: "использовать", d: "Take, hold, or deploy something as a means of accomplishing a purpose.", s: [] },
  "used": { t: "использованный", d: "Past of use.", s: [] },
  "using": { t: "использующий", d: "Present participle of use.", s: [] },
  "thought": { t: "мысль", d: "An idea or opinion produced by thinking.", s: [] },
  "area": { t: "область", d: "A region or part of a town, a country, or the world.", s: [] },
  "areas": { t: "области", d: "Plural of area.", s: [] },
  "result": { t: "результат", d: "A consequence, effect, or outcome.", s: [] },
  "results": { t: "результаты", d: "Plural of result.", s: [] },
  "mean": { t: "значить", d: "Intend to convey or refer to.", s: [] },
  "means": { t: "средства", d: "An action or system by which a result is brought about.", s: [] },
  "book": { t: "книга", d: "A written or printed work.", s: [] },
  "early": { t: "ранний", d: "Happening or done before the usual or expected time.", s: [] },
  "food": { t: "еда", d: "Any nutritious substance that people or animals eat.", s: [] },
  "history": { t: "история", d: "The study of past events.", s: [] },
  "toward": { t: "к", d: "In the direction of.", s: [] },
  "able": { t: "способный", d: "Having the power, skill, means, or opportunity.", s: [] },
  "second": { t: "второй", d: "Constituting number two in a sequence.", s: [] },
  "percent": { t: "процент", d: "By a specified amount in or for every hundred.", s: [] },
  "year": { t: "год", d: "The time taken by a planet to make one revolution around the sun.", s: [] },
  "economic": { t: "экономический", d: "Relating to economics or the economy.", s: [] },
  "strong": { t: "сильный", d: "Having the power to move heavy weights.", s: [] },
  "possible": { t: "возможный", d: "Able to be done.", s: [] },
  "important": { t: "важный", d: "Of great significance or value.", s: [] },
  "role": { t: "роль", d: "The function assumed or part played by a person or thing.", s: [] },
  "better": { t: "лучше", d: "Of a more excellent or effective type or quality.", s: [] },
  "term": { t: "термин", d: "A word or phrase used to describe a thing.", s: [] },
  "terms": { t: "термины", d: "Plural of term.", s: [] },
  "rate": { t: "ставка / темп", d: "A measure, quantity, or frequency.", s: [] },
  "rates": { t: "ставки / показатели", d: "Plural of rate.", s: [] },
  "low": { t: "низкий", d: "Of less than average height.", s: [] },
  "public": { t: "публичный", d: "Of or concerning the people as a whole.", s: [] },
  "read": { t: "читать", d: "Look at and comprehend the meaning of written matter.", s: [] },
  "law": { t: "закон", d: "The system of rules which a particular country recognizes.", s: [] },
  "keep": { t: "держать / хранить", d: "Have or retain possession of.", s: [] },
  "established": { t: "установленный", d: "Having been in existence for a long time.", s: [] },
  "local": { t: "местный", d: "Relating to a particular area.", s: [] },
  "almost": { t: "почти", d: "Not quite; very nearly.", s: [] },
  "full": { t: "полный", d: "Containing or holding as much or as many as possible.", s: [] },
  "light": { t: "свет", d: "The natural agent that stimulates sight.", s: [] },
  "far": { t: "далеко", d: "At, to, or by a great distance.", s: [] },
  "lead": { t: "вести", d: "Cause to go with one by holding them by the hand.", s: [] },
  "body": { t: "тело", d: "The physical structure of a person or an animal.", s: [] },
  "short": { t: "короткий", d: "Measuring a small distance from end to end.", s: [] },
  "open": { t: "открытый", d: "Allowing access, passage, or a view.", s: [] },
  "clear": { t: "ясный", d: "Easy to perceive, understand, or interpret.", s: [] },
  "several": { t: "несколько", d: "More than two but not many.", s: [] },
  "itself": { t: "сам", d: "Refers to the thing previously mentioned.", s: [] },
  "field": { t: "поле", d: "An area of open land.", s: [] },
  "pass": { t: "проходить", d: "Move or cause to move in a specified direction.", s: [] },
  "white": { t: "белый", d: "Of the colour of milk or fresh snow.", s: [] },
  "matter": { t: "материя / дело", d: "Physical substance in general.", s: [] },
  "political": { t: "политический", d: "Relating to the government or public affairs.", s: [] },
  "view": { t: "вид / взгляд", d: "The ability to see something.", s: [] },
  "main": { t: "главный", d: "Chief in size or importance.", s: [] },
  "likely": { t: "вероятный", d: "Probable.", s: [] },
  "special": { t: "специальный", d: "Better, greater, or otherwise different from what is usual.", s: [] },
  "black": { t: "черный", d: "Of the very darkest colour.", s: [] },
  "especially": { t: "особенно", d: "Used to single out one person or thing.", s: [] },
  "return": { t: "возвращение", d: "Come or go back to a place or person.", s: [] },
  "federal": { t: "федеральный", d: "Having or relating to a system of government.", s: [] },
  "added": { t: "добавленный", d: "Joined to something else.", s: [] },
  "working": { t: "работающий", d: "Having paid employment.", s: [] },
  "class": { t: "класс", d: "A set or category of things.", s: [] },
  "action": { t: "действие", d: "The fact or process of doing something.", s: [] },
  "higher": { t: "выше", d: "More high.", s: [] },
  "simple": { t: "простой", d: "Easily understood or done.", s: [] },
  "cost": { t: "стоимость", d: "Require the payment of.", s: [] },
  "centre": { t: "центр", d: "The middle point.", s: [] },
  "simply": { t: "просто", d: "Merely; just.", s: [] },
  "longer": { t: "дольше", d: "Measuring a great distance.", s: [] },
  "model": { t: "модель", d: "A three-dimensional representation.", s: [] },
  "range": { t: "диапазон", d: "The area of variation.", s: [] },
  "final": { t: "финальный", d: "Coming at the end.", s: [] },
  "hard": { t: "трудный / твердый", d: "Solid, firm, and rigid.", s: [] },
  "support": { t: "поддержка", d: "Bear all or part of the weight of.", s: [] },
  "stage": { t: "сцена / стадия", d: "A point, period, or step in a process.", s: [] },
  "century": { t: "век", d: "A period of one hundred years.", s: [] },
  "therefore": { t: "следовательно", d: "For that reason.", s: [] },
  "sound": { t: "звук", d: "Vibrations that travel through the air.", s: [] },
  "surface": { t: "поверхность", d: "The outside part or uppermost layer.", s: [] },
  "quality": { t: "качество", d: "The standard of something.", s: [] },
  "common": { t: "общий", d: "Occurring, found, or done often.", s: [] },
  "entire": { t: "весь", d: "With no part left out.", s: [] },
  "close": { t: "близкий / закрыть", d: "Only a short distance away.", s: [] },
  "design": { t: "дизайн", d: "A plan or drawing.", s: [] },
  "table": { t: "стол / таблица", d: "A piece of furniture with a flat top.", s: [] },
  "either": { t: "или / любой", d: "Used before the first of two alternatives.", s: [] },
  "neither": { t: "ни тот ни другой", d: "Not the one nor the other.", s: [] },
  "although": { t: "хотя", d: "In spite of the fact that.", s: [] },
  "plants": { t: "растения", d: "Living organisms of the kind exemplified by trees, shrubs, herbs.", s: ["flora"] },
  "plant": { t: "растение / завод", d: "A living organism.", s: ["flora"] },
  "direct": { t: "прямой", d: "Extending or moving from one place to another by the shortest way.", s: [] },
  "directly": { t: "напрямую", d: "Without changing direction.", s: [] },
  "taken": { t: "взятый", d: "Past participle of take.", s: [] },
  "science": { t: "наука", d: "The intellectual and practical activity encompassing systematic study.", s: [] },
  "scientific": { t: "научный", d: "Based on or characterized by the methods of science.", s: [] },
  "modern": { t: "современный", d: "Relating to the present or recent times.", s: [] },
  "similar": { t: "похожий", d: "Having a resemblance in appearance, character, or quantity.", s: [] },
  "normal": { t: "нормальный", d: "Conforming to a standard.", s: [] },
  "condition": { t: "условие / состояние", d: "The state of something.", s: [] },
  "conditions": { t: "условия", d: "Plural of condition.", s: [] },
  "method": { t: "метод", d: "A particular form of procedure.", s: [] },
  "central": { t: "центральный", d: "At the point or in the area that is in the middle.", s: [] },
  "region": { t: "регион", d: "An area or division.", s: [] },
  "list": { t: "список", d: "A number of connected items.", s: [] },
  "north": { t: "север", d: "The direction in which a compass needle points.", s: [] },
  "south": { t: "юг", d: "The direction towards the point of the horizon 90 degrees clockwise from east.", s: [] },
  "east": { t: "восток", d: "The direction where the sun rises.", s: [] },
  "west": { t: "запад", d: "The direction where the sun sets.", s: [] },
  "size": { t: "размер", d: "The relative extent of something.", s: [] },
  "particular": { t: "конкретный", d: "Used to single out an individual member of a specified group.", s: [] },
  "specifically": { t: "специально", d: "In a way that is exact and clear.", s: [] },
  "wrong": { t: "неправильный", d: "Not correct or true.", s: [] },
  "practice": { t: "практика", d: "The actual application or use of an idea.", s: [] },
  "critical": { t: "критический", d: "Expressing or involving an analysis of the merits and faults.", s: [] },
  "show": { t: "показывать", d: "Allow or cause something to be visible.", s: [] },
  "showed": { t: "показал", d: "Past of show.", s: [] },
  "shows": { t: "показывает", d: "Third person singular present of show.", s: [] },
  "demonstrate": { t: "демонстрировать", d: "Clearly show the existence or truth of something.", s: [] },
  "demonstrated": { t: "продемонстрировал", d: "Past of demonstrate.", s: [] },
  "explain": { t: "объяснять", d: "Make an idea clear to someone.", s: [] },
  "paper": { t: "бумага / статья", d: "Material manufactured in thin sheets.", s: [] },
  "papers": { t: "документы / статьи", d: "Plural of paper.", s: [] },
  "published": { t: "опубликованный", d: "Prepared and issued for public sale.", s: [] },
  "journal": { t: "журнал", d: "A newspaper or magazine.", s: [] },
  "online": { t: "онлайн", d: "Connected to a network.", s: [] },
  "source": { t: "источник", d: "A place, person, or thing from which something comes.", s: [] },
  "sources": { t: "источники", d: "Plural of source.", s: [] },
  "target": { t: "цель", d: "A person, object, or place selected as the aim.", s: [] },
  "targets": { t: "цели", d: "Plural of target.", s: [] },
  "answer": { t: "ответ", d: "A thing said, written, or done to deal with a question.", s: [] },
  "future": { t: "будущее", d: "The time regarded as still to come.", s: [] },
  "past": { t: "прошлое", d: "Gone by in time.", s: [] },
  "present": { t: "настоящее", d: "Existing or occurring now.", s: [] },
  "million": { t: "миллион", d: "The number equivalent to the product of a thousand and a thousand.", s: [] },
  "abducted": { t: "похищенный", d: "Taken away illegally by force.", s: ["seized", "kidnapped"] },
  "ability": { t: "способность", d: "The power or capacity to do something.", s: ["capability"] },
  "access": { t: "доступ", d: "The means or opportunity to approach or enter.", s: ["entry"] },
  "accurate": { t: "точный", d: "Correct in all details; exact.", s: ["precise"] },
  "accused": { t: "обвиняемый", d: "Charged with a fault or offense.", s: ["blamed"] },
  "achieved": { t: "достигнутый", d: "Successfully reach or look forward to.", s: ["attained"] },
  "activists": { t: "активисты", d: "People who campaign for change.", s: ["campaigners"] },
  "afflicted": { t: "пораженный", d: "Cause pain or suffering to.", s: ["troubled"] },
  "afford": { t: "позволить себе", d: "Have enough money to pay for.", s: ["manage"] },
  "agriculture": { t: "сельское хозяйство", d: "The practice of farming.", s: ["farming"] },
  "air": { t: "воздух", d: "The invisible gaseous substance surrounding the earth.", s: ["atmosphere"] },
  "alien": { t: "инопланетянин", d: "A being from another world.", s: ["extraterrestrial"] },
  "alterations": { t: "изменения", d: "The process of changing.", s: ["modifications"] },
  "alternative": { t: "альтернатива", d: "One of two or more available possibilities.", s: ["option"] },
  "analysis": { t: "анализ", d: "Detailed examination.", s: ["examination"] },
  "animal": { t: "животное", d: "A living organism that feeds on organic matter.", s: ["creature"] },
  "anticipated": { t: "ожидаемый", d: "Regard as probable; expect.", s: ["predicted"] },
  "anxiety": { t: "тревога", d: "A feeling of worry or unease.", s: ["concern"] },
  "appalling": { t: "ужасающий", d: "Causing shock or dismay; horrific.", s: ["terrible"] },
  "aquatic": { t: "водный", d: "Relating to water.", s: ["marine"] },
  "archive": { t: "архив", d: "A collection of historical records.", s: ["collection"] },
  "arguments": { t: "аргументы", d: "Reasons given with the aim of persuading.", s: ["reasoning"] },
  "assisted": { t: "вспомогательный", d: "Help or base something on.", s: ["aided"] },
  "astonishing": { t: "удивительный", d: "Extremely surprising.", s: ["amazing"] },
  "atmosphere": { t: "атмосфера", d: "The envelope of gases surrounding the earth.", s: ["air"] },
  "authorities": { t: "власти", d: "The power or right to give orders.", s: ["officials"] },
  "average": { t: "средний", d: "A number expressing the central value.", s: ["mean"] },
  "backed": { t: "поддержанный", d: "Supported by someone or something.", s: ["supported"] },
  "basic": { t: "базовый", d: "Forming an essential foundation.", s: ["fundamental"] },
  "beast": { t: "зверь / чудовище", d: "An animal, especially a large or dangerous one.", s: ["creature"] },
  "behaviour": { t: "поведение", d: "The way in which one acts.", s: ["conduct"] },
  "believes": { t: "верит", d: "Accept that something is true.", s: ["thinks"] },
  "biased": { t: "предвзятый", d: "Unfairly prejudiced.", s: ["one-sided"] },
  "billion": { t: "миллиард", d: "The number equivalent to a thousand million.", s: [] },
  "blanket": { t: "покров", d: "A thick layer of something.", s: ["layer"] },
  "buoyant": { t: "плавучий", d: "Able to stay afloat.", s: ["floating"] },
  "burst": { t: "лопнуть", d: "Break open suddenly.", s: ["shatter"] },
  "calving": { t: "отёл (льда)", d: "Splitting and shedding of a smaller ice mass.", s: ["breaking"] },
  "capacity": { t: "способность", d: "The ability to do something.", s: ["power"] },
  "carbon": { t: "углерод", d: "A chemical element.", s: [] },
  "cataclysm": { t: "катаклизм", d: "A violent natural event.", s: ["disaster"] },
  "cattle": { t: "скот", d: "Large ruminant animals like cows.", s: ["livestock"] },
  "centralisation": { t: "централизация", d: "Concentrating control in one place.", s: ["unification"] },
  "certain": { t: "определенный", d: "Known for sure; established.", s: ["sure"] },
  "changes": { t: "изменения", d: "The act of making or becoming different.", s: ["alterations"] },
  "cheaper": { t: "дешевле", d: "Lower in price.", s: ["inexpensive"] },
  "children": { t: "дети", d: "Young human beings.", s: ["kids"] },
  "circulation": { t: "циркуляция", d: "Movement around a closed system.", s: ["flow"] },
  "classify": { t: "классифицировать", d: "Arrange in categories.", s: ["categorize"] },
  "climate": { t: "климат", d: "Weather conditions in an area.", s: [] },
  "climatologists": { t: "климатологи", d: "Scientists who study climate.", s: [] },
  "collapsed": { t: "рухнул", d: "Fall down or give way.", s: ["crumbled"] },
  "colonised": { t: "колонизированный", d: "Settled in a new area.", s: ["populated"] },
  "compelled": { t: "принужденный", d: "Forced to do something.", s: ["obliged"] },
  "concertinas": { t: "гармошки", d: "Musical instruments like accordions.", s: [] },
  "conclusion": { t: "заключение", d: "A final decision or judgment.", s: ["judgment"] },
  "contaminated": { t: "загрязненный", d: "Made impure by contact.", s: ["polluted"] },
  "contemporaneous": { t: "одновременный", d: "Existing at the same time.", s: ["simultaneous"] },
  "conventional": { t: "общепринятый", d: "Based on what is generally done.", s: ["standard"] },
  "conveyor": { t: "конвейер", d: "A continuous moving band of fabric.", s: ["transporter"] },
  "cope": { t: "справляться", d: "Deal effectively with something difficult.", s: ["manage"] },
  "credentials": { t: "учетные данные", d: "Qualifications or background.", s: ["background"] },
  "crude": { t: "грубый", d: "Simple and basic.", s: ["primitive"] },
  "currents": { t: "течения", d: "Flowing of water in a direction.", s: ["streams"] },
  "damage": { t: "ущерб", d: "Physical harm caused to something.", s: ["harm"] },
  "debatable": { t: "спорный", d: "Open to discussion or argument.", s: ["arguable"] },
  "decidedly": { t: "решительно", d: "In a clear and definite way.", s: ["definitely"] },
  "decomposition": { t: "разложение", d: "The process of rotting; decay.", s: ["decay"] },
  "deep": { t: "глубокий", d: "Extending far down from the surface.", s: [] },
  "deforesting": { t: "вырубка лесов", d: "Clearing an area of trees.", s: ["clearing"] },
  "demise": { t: "кончина", d: "The end or failure of something.", s: ["death"] },
  "denser": { t: "плотнее", d: "More closely compacted in substance.", s: ["thicker"] },
  "density": { t: "плотность", d: "Compactness of a substance.", s: ["thickness"] },
  "description": { t: "описание", d: "A spoken or written representation.", s: ["account"] },
  "dilutes": { t: "разбавляет", d: "Make a liquid thinner or weaker.", s: ["weakens"] },
  "disaster": { t: "катастрофа", d: "A sudden accident or natural event.", s: ["calamity"] },
  "disgusting": { t: "отвратительный", d: "Arousing revulsion.", s: ["revolting"] },
  "disposing": { t: "утилизация", d: "Getting rid of something.", s: ["discarding"] },
  "doubt": { t: "сомнение", d: "A feeling of uncertainty.", s: ["uncertainty"] },
  "drainage": { t: "дренаж", d: "The action of draining something.", s: ["runoff"] },
  "dream": { t: "мечта / сон", d: "A series of thoughts; a cherished aspiration.", s: ["wish"] },
  "dwelling": { t: "жилище", d: "A house or place of residence.", s: ["home"] },
  "ecosystems": { t: "экосистемы", d: "Biological communities.", s: [] },
  "emissions": { t: "выбросы", d: "Production and discharge of gas.", s: ["discharge"] },
  "enforce": { t: "принуждать", d: "Compel observance of a law.", s: ["implement"] },
  "environmentalists": { t: "экологи", d: "People who protect the environment.", s: ["conservationists"] },
  "escape": { t: "побег", d: "An act of breaking free from confinement.", s: ["flight"] },
  "evaporation": { t: "испарение", d: "Process of turning liquid into vapor.", s: ["drying"] },
  "excrement": { t: "экскременты", d: "Waste discharged from the body.", s: ["waste"] },
  "exercises": { t: "упражнения / осуществляет", d: "Use or application of a faculty.", s: ["applies"] },
  "extinction": { t: "вымирание", d: "State of a species being extinct.", s: ["annihilation"] },
  "fairytale": { t: "сказка", d: "A fabricated story.", s: ["myth"] },
  "fashionable": { t: "модный", d: "Characteristic of current popular style.", s: ["stylish"] },
  "felled": { t: "срубленный", d: "Cut down (a tree).", s: [] },
  "fetid": { t: "зловонный", d: "Smelling extremely unpleasant.", s: ["stinking"] },
  "fires": { t: "пожары", d: "Combustion or burning.", s: ["flames"] },
  "fishery": { t: "рыболовство", d: "Place where fish are reared.", s: [] },
  "flooded": { t: "затопленный", d: "Covered with water.", s: ["submerged"] },
  "flout": { t: "пренебрегать", d: "Openly disregard a rule.", s: ["defy"] },
  "flow": { t: "поток", d: "The action of moving along in a steady stream.", s: ["current"] },
  "fluctuations": { t: "колебания", d: "Irregular rising and falling.", s: ["variations"] },
  "forestry": { t: "лесное хозяйство", d: "Science of caring for forests.", s: [] },
  "freezing": { t: "замораживание", d: "Process of turning into ice.", s: ["chilling"] },
  "garbage": { t: "мусор", d: "Wasted food and other refuse.", s: ["trash"] },
  "gases": { t: "газы", d: "Air-like fluid substances.", s: [] },
  "genetically": { t: "генетически", d: "In a way that relates to genes.", s: [] },
  "global": { t: "глобальный", d: "Relating to the whole world.", s: ["worldwide"] },
  "governor": { t: "губернатор", d: "The head of a state or city.", s: ["leader"] },
  "grandchildren": { t: "внуки", d: "Children of one's children.", s: [] },
  "great": { t: "великий", d: "An extent, amount, or intensity considerably above normal.", s: ["big"] },
  "guide": { t: "руководство", d: "A thing that shows the way.", s: ["manual"] },
  "habitats": { t: "среды обитания", d: "Natural homes for organisms.", s: ["homes"] },
  "health": { t: "здоровье", d: "State of being free from illness.", s: ["well-being"] },
  "heat": { t: "тепло", d: "Quality of being hot.", s: ["warmth"] },
  "hovels": { t: "лачуги", d: "Small, squalid dwellings.", s: ["shacks"] },
  "hurricanes": { t: "ураганы", d: "Storms with violent winds.", s: ["cyclones"] },
  "icebergs": { t: "айсберги", d: "Large floating masses of ice.", s: [] },
  "imminent": { t: "неизбежный", d: "About to happen.", s: ["approaching"] },
  "indisputable": { t: "неоспоримый", d: "Unable to be challenged.", s: ["undeniable"] },
  "industrialised": { t: "индустриализированный", d: "Develop industries.", s: ["developed"] },
  "inevitably": { t: "неизбежно", d: "As is certain to happen.", s: ["necessarily"] },
  "infect": { t: "заражать", d: "Contaminate with disease.", s: ["pollute"] },
  "influence": { t: "влияние", d: "The capacity to have an effect.", s: ["effect"] },
  "inflicted": { t: "нанесенный", d: "Cause something unpleasant.", s: ["imposed"] },
  "injurious": { t: "вредоносный", d: "Causing damage or harm.", s: ["harmful"] },
  "intervals": { t: "интервалы", d: "Spaces of time between events.", s: ["gaps"] },
  "inventions": { t: "изобретения", d: "Actions of creating something new.", s: ["creations"] },
  "irrelevant": { t: "неуместный", d: "Not connected or relevant.", s: ["unrelated"] },
  "irregular": { t: "нерегулярный", d: "Not occurring at fixed intervals.", s: ["uneven"] },
  "landscape": { t: "пейзаж", d: "Visible features of an area of land.", s: ["scenery"] },
  "legislation": { t: "законодательство", d: "Laws considered collectively.", s: ["laws"] },
  "likens": { t: "уподобляет", d: "Point out the resemblance.", s: ["compares"] },
  "link": { t: "связь", d: "A relationship or connection.", s: ["connection"] },
  "lives": { t: "жизни", d: "The existence of individuals.", s: [] },
  "logging": { t: "лесозаготовки", d: "Cutting down trees.", s: ["lumbering"] },
  "lost": { t: "потерянный", d: "Unable to be found.", s: ["missing"] },
  "luxury": { t: "роскошь", d: "State of great comfort.", s: ["extravagance"] },
  "magnitude": { t: "величина", d: "The great size or extent.", s: ["scale"] },
  "manifestly": { t: "явно", d: "In a way that is clear or obvious.", s: ["clearly"] },
  "meandering": { t: "извилистый", d: "Following a winding course.", s: ["winding"] },
  "measurements": { t: "измерения", d: "Actions of measuring something.", s: [] },
  "methodology": { t: "методология", d: "System of methods used.", s: ["procedure"] },
  "miles": { t: "мили", d: "Unit of linear measure.", s: [] },
  "millennium": { t: "тысячелетие", d: "A period of a thousand years.", s: [] },
  "mining": { t: "добыча", d: "Obtaining minerals from a mine.", s: ["extraction"] },
  "naivety": { t: "наивность", d: "Lack of experience or wisdom.", s: ["innocence"] },
  "natural": { t: "естественный", d: "Existing in or caused by nature.", s: ["organic"] },
  "negligible": { t: "незначительный", d: "So small as to be unimportant.", s: ["trivial"] },
  "neighbourhoods": { t: "районы", d: "Districts within a town.", s: ["districts"] },
  "network": { t: "сеть", d: "Group of interconnected things.", s: ["web"] },
  "news": { t: "новости", d: "Newly received information.", s: ["report"] },
  "notorious": { t: "пресловутый", d: "Famous for some bad quality.", s: ["infamous"] },
  "nutrients": { t: "питательные вещества", d: "Substances providing nourishment.", s: [] },
  "obscure": { t: "неясный", d: "Not discovered or known about.", s: ["unclear"] },
  "ocean": { t: "океан", d: "A very large expanse of sea.", s: [] },
  "offal": { t: "потроха", d: "Internal organs of an animal.", s: ["innards"] },
  "oil": { t: "нефть", d: "Viscous liquid derived from petroleum.", s: ["fuel"] },
  "overfishing": { t: "перелов", d: "Depleting the stock of fish.", s: [] },
  "overpowering": { t: "непреодолимый", d: "Extremely strong or intense.", s: ["overwhelming"] },
  "permanent": { t: "постоянный", d: "Lasting or intended to last unchanged.", s: ["stable"] },
  "picture": { t: "картина", d: "A painting or drawing.", s: ["image"] },
  "plastics": { t: "пластик", d: "Synthetic materials.", s: [] },
  "poison": { t: "яд", d: "Substance causing illness or death.", s: ["toxin"] },
  "polluted": { t: "загрязненный", d: "Contaminated with harmful substances.", s: ["dirty"] },
  "ponder": { t: "обдумывать", d: "Think about something carefully.", s: ["consider"] },
  "predators": { t: "хищники", d: "Animals that prey on others.", s: ["hunters"] },
  "preserve": { t: "сохранять", d: "Maintain in its original state.", s: ["protect"] },
  "pristine": { t: "первозданный", d: "In its original condition.", s: ["pure"] },
  "prohibiting": { t: "запрещающий", d: "Formally forbidding by law.", s: ["banning"] },
  "prosper": { t: "процветать", d: "Flourish physically; thrive.", s: ["thrive"] },
  "pundits": { t: "эксперты", d: "Experts frequently giving opinions.", s: ["authorities"] },
  "putrefying": { t: "гниение", d: "Decaying and emitting a smell.", s: ["rotting"] },
  "puzzle": { t: "головоломка", d: "A mystery or enigma.", s: ["mystery"] },
  "recent": { t: "недавний", d: "Having happened lately.", s: ["late"] },
  "reckoning": { t: "расчет", d: "Action of calculating or estimating.", s: ["calculation"] },
  "reclaim": { t: "вернуть себе", d: "Retrieve or recover lost things.", s: ["recover"] },
  "recover": { t: "восстанавливаться", d: "Return to a normal state.", s: ["recuperate"] },
  "regulations": { t: "правила", d: "Rules made by authority.", s: ["rules"] },
  "report": { t: "отчет", d: "An account given of a matter.", s: ["account"] },
  "residential": { t: "жилой", d: "Designed for people to live in.", s: [] },
  "retrospective": { t: "ретроспективный", d: "Looking back on past events.", s: ["backward-looking"] },
  "rich": { t: "богатый", d: "Having a great deal of money.", s: ["wealthy"] },
  "rivers": { t: "реки", d: "Large natural streams of water.", s: [] },
  "salinity": { t: "соленость", d: "Concentration of salts in water.", s: ["saltiness"] },
  "sceptical": { t: "скептический", d: "Not easily convinced.", s: ["doubtful"] },
  "scientists": { t: "ученые", d: "Experts in science.", s: [] },
  "sea": { t: "море", d: "The expanse of salt water.", s: ["ocean"] },
  "sewage": { t: "сточные воды", d: "Waste water and excrement.", s: ["waste"] },
  "shacks": { t: "хижины", d: "Roughly built huts.", s: ["huts"] },
  "shrug": { t: "пожать плечами", d: "Dismiss as unimportant.", s: ["dismiss"] },
  "sign": { t: "знак / признак", d: "Object, quality, or event indicating something.", s: ["signal"] },
  "slum": { t: "трущобы", d: "Squalid urban street inhabited by the poor.", s: ["ghetto"] },
  "smell": { t: "запах", d: "Faculty of perceiving odors.", s: ["scent"] },
  "smog": { t: "смог", d: "Fog intensified by pollutants.", s: ["haze"] },
  "snap": { t: "внезапное похолодание", d: "Sudden period of cold weather.", s: ["spell"] },
  "spectre": { t: "призрак", d: "Widely feared unpleasant occurrence.", s: ["threat"] },
  "species": { t: "виды", d: "Group of similar living organisms.", s: ["types"] },
  "speed": { t: "скорость", d: "Rate at which someone moves.", s: ["tempo"] },
  "stench": { t: "вонь", d: "Strong and unpleasant smell.", s: ["stink"] },
  "streets": { t: "улицы", d: "Public roads in a city.", s: ["roads"] },
  "stubborn": { t: "упрямый", d: "Difficult to remove or cure.", s: ["persistent"] },
  "stutter": { t: "запинка", d: "Period of unsteady progress.", s: ["glitch"] },
  "substantial": { t: "существенный", d: "Of considerable importance.", s: ["significant"] },
  "suggests": { t: "предполагает", d: "Put forward for consideration.", s: ["proposes"] },
  "sums": { t: "суммы / расчеты", d: "Arithmetical calculations.", s: ["calculations"] },
  "survey": { t: "опрос / обзор", d: "General view or description.", s: ["review"] },
  "tanneries": { t: "кожевенные заводы", d: "Places where hides are tanned.", s: [] },
  "terminal": { t: "смертельный", d: "Predicted to lead to death.", s: ["fatal"] },
  "terrestrial": { t: "земной", d: "On or relating to the earth.", s: ["land-based"] },
  "thawing": { t: "оттаивание", d: "Process of ice becoming liquid.", s: ["melting"] },
  "thermohaline": { t: "термохалинный", d: "Relating to heat and salt.", s: [] },
  "threaten": { t: "угрожать", d: "Intend to take hostile action.", s: ["menace"] },
  "tonnes": { t: "тонны", d: "Metric units of weight.", s: [] },
  "transient": { t: "преходящий", d: "Lasting only for a short time.", s: ["temporary"] },
  "trawling": { t: "траление", d: "Fishing with a large net.", s: [] },
  "trees": { t: "деревья", d: "Perennial plants with a trunk.", s: [] },
  "tundra": { t: "тундра", d: "Treeless Arctic region.", s: ["steppes"] },
  "turbulent": { t: "турбулентный", d: "Characterized by disorder.", s: ["unstable"] },
  "uncannily": { t: "сверхъестественно", d: "In a strange or mysterious way.", s: ["eerily"] },
  "underestimated": { t: "недооцененный", d: "Estimate to be smaller than it is.", s: ["undervalued"] },
  "unforeseen": { t: "непредвиденный", d: "Not anticipated or predicted.", s: ["unexpected"] },
  "unstable": { t: "нестабильный", d: "Prone to change or fail.", s: ["unsteady"] },
  "untreated": { t: "необработанный", d: "Not received treatment.", s: ["raw"] },
  "vagaries": { t: "капризы", d: "Inexplicable changes in a situation.", s: ["quirks"] },
  "weeds": { t: "сорняки", d: "Wild plants growing where unwanted.", s: [] },
  "wildernesses": { t: "пустыни / дикая местность", d: "Wild and uncultivated regions.", s: ["wilds"] },
  "wisdom": { t: "мудрость", d: "Quality of having experience.", s: ["intelligence"] },
  "world": { t: "мир", d: "The earth and all its inhabitants.", s: ["globe"] }
};

export const PASSAGES: Passage[] = [
  {
    id: 1,
    title: "Ecosystems can fight back",
    content: [
      "A Conventional wisdom is often a poor guide. For one thing it suggests that human damage to the world's species, habitats and ecosystems is terminal: that when things are lost, they are lost for ever. But oil spills of the sort that now threaten the Timor Sea, forest fires like those that recently afflicted Greece, and other man-made and man-assisted threats to wildlife are transient. Except in those cases in which a species is driven to extinction, the Earth's ability to shrug such things off is often underestimated.",
      "B Alan Weisman shows this in his book, \"The World Without Us\", which illustrates nature's great capacity to recover. Have mankind abducted by aliens or wiped out by some Homo sapiens-specific virus, and nature, Mr Weisman reckons, would reclaim its territory with surprising speed, as weeds colonised pavements, rivers flooded subway tunnels and buildings burst as they were played like concertinas by a cycle of freezing and thawing. By Mr Weisman's reckoning, residential neighbourhoods would return to forest in 500 years and only the most stubborn of human inventions, such as certain plastics, would prove permanent.",
      "C Mr Weisman's conclusion was backed up earlier this year by a study published in the Public Library of Science by Holly Jones and Oswald Schmitz, of Yale's School of Forestry and Environmental Studies. They used Web of Science, an online journal archive, to gather a set of 240 peer-reviewed scientific papers that measured recovery rates in large terrestrial and aquatic ecosystems. The data thus available included work on agriculture, deforestation, the introduction of invasive species, logging, mining, oil spills, overfishing and the damage done to seabeds by trawling, as well as, for comparison, naturally occurring disasters such as hurricanes.",
      "D The pair measured 94 aspects of how ecosystems are put together, including the ways in which nutrients cycle within them, the rates at which decomposition takes place and the sizes of their plant and animal populations, so that they could classify whether, and how fast, an area had recovered. They found that 83 of the 240 papers demonstrated complete recovery, while 90 showed a mixed response. Only 67 showed no recovery at all and, as the authors explain, more would have recovered if the projects had continued for long enough to track the changes in ecosystems that respond more slowly, such as forests.",
      "E Ecosystems exposed to more than one pressure, such as a forest that is first felled and then used for agriculture, took the longest to recover. Even in those cases, though, the average recovery time was, at 56 years, within a human lifetime. Sites that experienced single threats typically recovered in less than 20 years. The researchers found that recovery rates are influenced more by the type of ecosystem than by the magnitude of the damage inflicted upon it. Forests, for example, take longer to renew (42 years) than ocean floors (typically less than ten) regardless of the scale of the stresses inflicted on them.",
      "F Some commentators are sceptical about such positive findings. They point out that, of necessity, the study's retrospective methodology includes papers published before researchers were required to declare any competing interests. This may have allowed, for example, an oil company to produce a report that plays down the damage done by a spillage. But such biased individual reports would be unlikely to affect the overall findings of a large study like this one.",
      "G Critics also question whether total ecological recovery really has been achieved as often as Ms Jones and Dr Schmitz suggest, and point to examples where it manifestly has not, such as the cod fishery of the Grand Banks, off the coast of Newfoundland, which collapsed in 1992. Almost two decades on, the cod show no sign of recovery, perhaps because new predators, such as dogfish, now dominate the waters.",
      "H It is true, though, that the question of what is pristine or natural can be debatable. A good example of this, which Mr Weisman uses in his book, is Dartmoor, a national park in the south-west of England. Dartmoor is considered by many to be one of Britain's great nature wildernesses. In fact, it is a human construction, formed by tens of thousands of years' worth of alterations such as burning and agriculture. But it is in its current state, rather than as the forest it once was, that people wish to preserve it. Ms Jones and Dr Schmitz point out that most conservation work is not actually concerned with returning landscapes to their natural or prehuman states and \"instead use contemporaneous reference systems as targets\".",
      "I Despite their study's limitations, and the difficulty of measuring recovery and choosing targets, Ms Jones's and Dr Schmitz's findings are good news for conservationists. But the final word of advice belongs to Mr Weisman as he invites people to ponder an alternative to his post-human future: \"Since we're imagining, why not dream of a way for nature to prosper that doesn't depend on our demise?"
    ],
    questionInstruction: "Answer the following questions based on Section 1.",
    questions: [
      { id: "q1", label: "1", type: "MATCHING", text: "Which paragraph contains the main factor affecting recovery rates?", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"] },
      { id: "q2", label: "2", type: "MATCHING", text: "Which paragraph contains a picture of urban life taken over by nature?", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"] },
      { id: "q3", label: "3", type: "MATCHING", text: "Which paragraph contains examples of environmental damage caused by humans?", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"] },
      { id: "q4", label: "4", type: "MATCHING", text: "Which paragraph contains positive results from a study?", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"] },
      { id: "q5", label: "5", type: "MATCHING", text: "Which paragraph contains the kind of information gathered from scientific records?", options: ["A", "B", "C", "D", "E", "F", "G", "H", "I"] },
      { id: "q6", label: "6", type: "GAP_FILL", text: "Approximate recovery time for ecosystems which experience no more than one pressure is ___________." },
      { id: "q7", label: "7", type: "GAP_FILL", text: "Some critics claim the positive results may be influenced by some companies understating the ___________ they have caused." },
      { id: "q8", label: "8", type: "GAP_FILL", text: "The cod fishery of the Grand Banks is an example of where there has not been a complete ___________." },
      { id: "q9", label: "9", type: "GAP_FILL", text: "Dartmoor was originally ___________." },
      { id: "q10", label: "10", type: "GAP_FILL", text: "Preserving or returning [landscape] to a ___________ condition..." },
      { id: "q11", label: "11", type: "GAP_FILL", text: "...rather than to their original ___________." },
      { id: "q12", label: "12", type: "GAP_FILL", text: "Despite problems with ___________ and recovery measurement..." },
      { id: "q13", label: "13", type: "GAP_FILL", text: "...this latest study is a source of optimism for ___________." }
    ],
    offlineQuiz: [
      { word: "terminal", question: "What does 'terminal' mean in the text?", options: ["Temporary", "Lethal/Final", "Beginning", "Scientific"], correctAnswerIndex: 1, explanation: "Paragraph A: Conventional wisdom suggests damage is terminal (lost forever)." },
      { word: "transient", question: "If a threat is 'transient', it is:", options: ["Permanent", "Dangerous", "Short-lived", "Global"], correctAnswerIndex: 2, explanation: "Paragraph A: Threats to wildlife are transient (temporary)." }
    ]
  },
  {
    id: 2,
    title: "Poor countries environmental problems",
    content: [
      "A \"THE centralisation of population in great cities exercises of itself an unfavourable influence,\" wrote Friedrich Engels in 1844. \"All putrefying vegetable and animal substances give off gases decidedly injurious to health, and if these gases have no free way of escape, they inevitably poison the atmosphere The poor are obliged to throw all offal and garbage, all dirty water, often all disgusting drainage and excrement into the streets, being without other means of disposing of them; they are thus compelled to infect the region of their own dwelling.\"",
      "B Much of Engels's writing seems irrelevant today, but his description of working-class life in 19th-century London paints an uncannily accurate picture of slum life in developing countries at the end of the 20th century. In the Klong Toey district of Bangkok, the stench from the rotting rubbish and fetid water that collect between the shacks is overpowering. In the north of Mexico city, near Santa Fe, hovels cling to the sides of a steep valley which most days is choked with smog, and streams of untreated sewage run down to the river below. In the Moroccan town of Marrakesh, the smell of rotting cattle flesh surrounds tanneries for miles around.",
      "C Conventional wisdom has it that concern for the environment is a luxury only the rich world can afford; that only people whose basic needs for food and shelter have been met (as well as, perhaps, some not-so-basic ones for things like cars and televisions) can start worrying about the health of the planet but surely developing countries, too, should be thinking about the environment. True, in the rich countries a strong environmental movement did not emerge until long after they had become industrialised, a stage that many developing countries have yet to reach. And true, many of the developed world's environmental concerns have little to do with immediate threats to its inhabitants' well-being. People worry about whether carbon-dioxide emissions might lead to a warmer climate next century, or whether genetically engineered crops might have unforeseen consequences for the ecosystem. That is why, when rich-world environmentalists campaign against pollution in poor countries, they are often accused of naivety. Such countries, the critics say, have more pressing concerns, such as getting their people out of poverty.",
      "D The environmental problems that developing countries should worry about however are different from those that western pundits have fashionable arguments over. They are not about potential problems in the next century, but about indisputable harm being caused today by, above all, contaminated water and polluted air. Contrary to conventional wisdom, solving such problems need not hurt economic growth; indeed dealing with them now will generally be cheaper than leaving them to cause further harm.",
      "E In most developing countries pollution seems to be getting worse, not better. Most big cities in Latin America, for example, are suffering rising levels of air pollution. Populations in poor countries are growing so fast that improvements in water supply have failed to keep up with the number of extra people. Worldwide, about a billion people still have no access to clean water, and water contaminated by sewage is estimated to kill some 2m children every year. Throughout Latin America, Asia and Africa, forests are disappearing, causing not just long-term concern about climate change but also immediate economic damage. Forest fires in Indonesia last year produced a huge blanket of smog that enveloped much of South-East Asia and kept the tourists away. It could happen again, and probably will.",
      "F Recent research suggests that pollution in developing countries is far more than a minor irritation: it imposes a heavy economic cost. A World Bank study last year put the cost of air and water pollution in China at $54 billion a year, equivalent to an astonishing 8% of the country's GDP. Another study estimated the health costs of air pollution in Jakarta and Bangkok in the early 1990s at around 10% of these cities' income. These are no more than educated guesses, but whichever way the sums are done, the cost is not negligible.",
      "G The growth in environmental problems in developing countries has been matched by a rise in local anxiety about them. In recent years hundreds of environmental lobby groups have sprung up in Latin America and Asia. Some of these are offshoots of rich-world groups such as Greenpeace, which now has offices in 11 developing countries. But many of the new groups are home-grown, drawing support from people increasingly worried about the effect of pollution on their health.",
      "H In Bolivia, Mexico and Brazil, green activists have recently entered government. Bangkok's people, frustrated by the city's notorious congestion and pollution, have elected a governor with strong green credentials, Bichit Rattanakorn, who has threatened to \"name and shame\" firms that flout pollution rules. He is urging other Asian cities at an earlier stage of industrialisation \"not to follow in our footsteps\".",
      "I From Brazil to China, governments are passing increasingly tough environmental regulations, many of them modelled on green standards in Europe and North America. Often this is an empty gesture: many countries are unwilling or unable to enforce green regulations. Brazilian politicians may have felt a warm glow in January when they passed a law against \"environmental crimes\", but Brazil already has legislation prohibiting Amazon landowners from deforesting more than 20% of their land. That has done nothing to stop many of them cutting down all their trees."
    ],
    questionInstruction: "Match headings (i-x) to paragraphs A-I and answer T/F/NG questions.",
    questions: [
      { id: "q14", label: "14", type: "MATCHING", text: "Paragraph A", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q15", label: "15", type: "MATCHING", text: "Paragraph B", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q16", label: "16", type: "MATCHING", text: "Paragraph C", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q17", label: "17", type: "MATCHING", text: "Paragraph D", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q18", label: "18", type: "MATCHING", text: "Paragraph E", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q19", label: "19", type: "MATCHING", text: "Paragraph F", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q20", label: "20", type: "MATCHING", text: "Paragraph G", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q21", label: "21", type: "MATCHING", text: "Paragraph H", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q22", label: "22", type: "MATCHING", text: "Paragraph I", options: ["i", "ii", "iii", "iv", "v", "vi", "vii", "viii", "ix", "x"] },
      { id: "q23", label: "23", type: "TRUE_FALSE_NOT_GIVEN", text: "Two million children die every year from water pollution in Latin America." },
      { id: "q24", label: "24", type: "TRUE_FALSE_NOT_GIVEN", text: "Air pollution will probably have a negative effect on tourism in Indonesia for many years." },
      { id: "q25", label: "25", type: "TRUE_FALSE_NOT_GIVEN", text: "Bangkok's governor intends to punish companies which break laws on green issues." },
      { id: "q26", label: "26", type: "TRUE_FALSE_NOT_GIVEN", text: "Brazil needs stronger laws in order to make progress on its environmental problems." }
    ],
    offlineQuiz: [
      { word: "hovels", question: "What is a 'hovel'?", options: ["A luxury apartment", "A scientific lab", "A small, squalid dwelling", "A government office"], correctAnswerIndex: 2, explanation: "Paragraph B: Hovels cling to the sides of a steep valley." },
      { word: "negligible", question: "If a cost is 'negligible', it is:", options: ["Extremely high", "Unimportant/Tiny", "Mandatory", "Rising"], correctAnswerIndex: 1, explanation: "Paragraph F: Whichever way sums are done, the cost is not negligible (it is significant)." }
    ]
  },
  {
    id: 3,
    title: "Climate change and the Atlantic",
    content: [
      "Are changes in ocean circulation about to turn our lives upside down, or is this something only our grandchildren will have to cope with? This vital question is in doubt because the behaviour of ocean currents is still remarkably obscure. On a crude level, the oceans of the world are linked together by a network of currents sometimes called the global conveyor, with warm surface flows connecting to cold deep currents. The conveyor is driven by winds and by a more complicated process called thermohaline circulation - and this is the process that has climatologists worried.",
      "As its name implies, thermohaline circulation depends on heat and salt. An offshoot of the Gulf Stream called the North Atlantic Drift flows all the way to the seas off Greenland and Norway. Evaporation makes the water saltier, so as it is chilled by Arctic winds it becomes denser than the waters underneath it and sinks. It then spills back southward over the undersea ledges between Greenland and Scotland to form a slow, cold, undersea river called the North Atlantic Deep Water. This flows all the way to the Southern Ocean, with some water going as far the Indian Ocean, where it gradually wells up again, perhaps a millennium after it sank.",
      "The weak link is the sinking process. Climate change is injecting ever more fresh water into the Arctic by increasing river flows and accelerating the calving of icebergs from Greenland. This fresh water dilutes the North Atlantic Drift, reducing its density and making it more buoyant. If the fresh water input reaches a critical rate, around 100,000 tonnes per second, sinking could stop entirely. The northern branch of the conveyor would stop, and warm tropical waters would no longer flow past the west coast of Europe.",
      "With that million-gigawatt heat supply switched off, climate models suggest that air temperatures in the region could fall by between 5 and 10 °C, and parts of the US and Canada would suffer too. A switch-off like this is blamed for a cold snap 12,000 years ago called the Younger Dryas, which turned the forests of Scandinavia into tundra. Could it be happening again? That spectre was raised in December by Harry Bryden of the National Oceanography Centre in Southampton, UK. His team took a ship from Florida to the coast of North Africa, stopping at 120 points en route to lower a bundle of instruments all the way to the sea floor. The researchers compared their results with similar measurements made at irregular intervals since 1957. According to their analysis, the deep, cold return leg of the circulation has weakened by 30 per cent. If that has slowed, they reasoned, then the northward branch of warm water must have slowed too.",
      "In fact, the slowdown seems to have started nearly a decade ago. When the US National Oceanic & Atmospheric Administration made a similar survey of the Atlantic in 1998 it was interested in carbon dioxide levels and did not calculate the flow rate. When Bryden's team did the sums, they found the flow had been relatively steady between 1957 and 1992, dropped off by 1998 and remained low. Bryden's paper prompted some nervous press coverage. \"There were alarming stories saying that the sky is falling,\" says Carl Wunsch, a physical oceanographer at Massachusetts Institute of Technology. \"It's a complicated story reduced to a fairytale\". In fact, Bryden's measurements are not proof of imminent cataclysm.",
      "One question mark is whether his team has simply seen short-term fluctuations in the ocean. \"The ocean is a very turbulent beast. We tend to assume that at great depth it is quiet, but that's not necessarily so,\" says Stefan Rahmstorf of the University of Potsdam in Germany. Wunsch likens it to the vagaries of the weather: \"It might get colder for a few days in England, but you don't necessarily say we're entering a new ice age.\"",
      "Bryden, however, thinks his team has found more than a stutter. \"If we just had the 1998 data we'd be nervous, but 2004 is similar to 1998,\" he says.",
      "There are other reasons to be cautious. Climate models do not predict any substantial slowdown in Atlantic currents until near the end of this century. \"It would mean all our models were wrong,\" says Rahmstorf. Bryden thinks they might well be: \"I think if we measure a slowdown, the models will follow.\"",
      "The trouble for Bryden is that not all observations fit in with his conclusions. If less warm water is flowing north, the seas off western Europe ought to be cooler than normal. They are not. In fact, these waters are slightly warmer than a decade ago. And direct measurements of the cold, deep currents that spill southwards over the ledges joining Scotland, Iceland and Greenland do not show a downward trend. Although these currents did slow between 1995 and 2000, they have picked up again. \"We are faced with conflicting evidence,\" says Rahmstorf.",
      "How to resolve this conflict? It is possible that Bryden's group has got its physics wrong. Like other groups, the team did not measure flow rates directly, but instead calculated them from measurements of temperature and salinity. Rahmstorf and Wunsch both point out that these calculations rely on assumptions that are far from proven.",
      "Alternatively, it could be that the currents are changing in ways that no one has anticipated. There is a vast stretch of ocean between Bryden's measurements at 25° north and the overspill at around 65°. In between, the warm surface current becomes meandering and unstable, and difficult to measure, says oceanographer Tore Furevik of the University of Bergen in Norway. \"There are certainly large changes going on beneath the surface of the North Atlantic, but we are still missing too many pieces in the puzzle to get the picture clear,\" he says.",
      "For the moment, this rather unsatisfactory answer is the best we have. Oceanographers and climate scientists agree that thermohaline circulation will slow as the world warms, but most think it will happen later rather than sooner. In its report due next year, the Intergovernmental Panel on Climate Change is likely to predict a slowdown of at most 50 per cent by the end of this century."
    ],
    questionInstruction: "Answer Yes/No/NG and Match names to sentences.",
    questions: [
      { id: "q27", label: "27", type: "YES_NO_NOT_GIVEN", text: "Climate specialists are predominantly worried about the affect of the wind on the network of ocean currents." },
      { id: "q28", label: "28", type: "YES_NO_NOT_GIVEN", text: "The North Atlantic Deep Water is formed from the Gulf Stream." },
      { id: "q29", label: "29", type: "YES_NO_NOT_GIVEN", text: "Climate change is indirectly making the North Atlantic Drift lighter." },
      { id: "q30", label: "30", type: "YES_NO_NOT_GIVEN", text: "Younger Dryas was caused by a warming of tropical waters off the west coast of Europe." },
      { id: "q31", label: "31", type: "YES_NO_NOT_GIVEN", text: "Some critics believe that Bryden's research does not cover a sufficiently long period of time." },
      { id: "q32", label: "32", type: "YES_NO_NOT_GIVEN", text: "Today, the seas around the west of Europe are moving more quickly than 10 years ago." },
      { id: "q33", label: "33", type: "YES_NO_NOT_GIVEN", text: "Bryden's data is based on changes in salt levels." },
      { id: "q34", label: "34", type: "YES_NO_NOT_GIVEN", text: "The conflicting evidence could be due to the difference between Bryden's and Furevik's measurement techniques." },
      { id: "q35", label: "35", type: "CLASSIFICATION", text: "used data collected at uneven time periods", options: ["Rahmstorf", "Bryden", "Furevik", "Wunsch"] },
      { id: "q36", label: "36", type: "CLASSIFICATION", text: "believes that a lot more information needs to be gathered", options: ["Rahmstorf", "Bryden", "Furevik", "Wunsch"] },
      { id: "q37", label: "37", type: "CLASSIFICATION", text: "points out that deep oceans are quite unstable", options: ["Rahmstorf", "Bryden", "Furevik", "Wunsch"] },
      { id: "q38", label: "38", type: "CLASSIFICATION", text: "compares Bryden's findings to changes in the weather", options: ["Rahmstorf", "Bryden", "Furevik", "Wunsch"] },
      { id: "q39", label: "39", type: "CLASSIFICATION", text: "relies a degree of guesswork", options: ["Rahmstorf", "Bryden", "Furevik", "Wunsch"] },
      { id: "q40", label: "40", type: "CLASSIFICATION", text: "criticises the way Bryden's work was reported", options: ["Rahmstorf", "Bryden", "Furevik", "Wunsch"] }
    ],
    offlineQuiz: [
      { word: "thermohaline", question: "What does 'thermohaline' refer to?", options: ["Wind patterns", "Temperature and salt", "Marine life", "Deep sea volcanos"], correctAnswerIndex: 1, explanation: "Text: thermohaline circulation depends on heat and salt." },
      { word: "cataclysm", question: "A 'cataclysm' is a:", options: ["Minor error", "Violent natural event", "Scientific theory", "Slow change"], correctAnswerIndex: 1, explanation: "In this context, it refers to an imminent disaster or large-scale violent event." }
    ]
  }
];
